#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Variables
FILE_PATH="$1"
REMOTE_IP="$2"   
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file using scp with the provided SSH key and ignoring strict host key checking
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$REMOTE_IP:~"

# Check if the scp command was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
    exit 1
fi
