#!/usr/bin/env bash

# Ensure the script is run with root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Update package list and install Nginx
apt-get -y update
apt-get -y install nginx

# Change default html file
echo 'Hello World!' > /var/www/html/index.html

# Configure /redirect_me to redirect to another page with a 301 Moved Permanently status
sed -i "/server_name _;/ a\\\tlocation /redirect_me {\n\t\treturn 301 https://github.com/chiemezie1;\n\t}" /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
service nginx restart

# Verify the redirection
curl -sI localhost/redirect_me
