#!/usr/bin/env bash
# This script installs and configures HAProxy on an Ubuntu server

# Update and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Append HAProxy configuration using echo and redirection
echo "
# Frontend configuration
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

# Backend configuration
backend http_back
    balance roundrobin
    server web-01 100.26.157.222:80 check
    server web-02 3.94.185.154:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

#HAProxy service is enabled to start on boot.
echo -e "ENABLED=1" >> /etc/default/haproxy

# Restart HAProxy to apply the configuration
sudo service haproxy restart

echo "HAProxy has been configured and started."
