#!/usr/bin/env bash
# Starts nginx as user nginx on port 8080

# Stop Apache if it's running
service apache2 stop

# Update Nginx configuration to run as nginx user and listen on port 8080
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
